
version: 1.11.{build}

branches:
  only:
    - master

# Do not build fature branch with open Pull requests
skip_branch_with_pr: true

image: Visual Studio 2017

configuration: Release

clone_folder: c:\projects\TFF

install: 
- "SET PATH=C:\\Program Files\\dotnet\\bin;%PATH%"
- "SET PATH=C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\;%PATH%"
- cmd: FSI.exe c:\projects\TFF\setup\setup.fsx

build_script:
- dotnet restore
- dotnet build

after_build:
- dotnet test
- dotnet pack

